language: java
jdk:
  - openjdk8
install: true
script:
  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
cache:
  directories:
    - '$HOME/.m2'
after_success:
  - mvn clean test jacoco:report coveralls:report